spring.application.name=collegeops

spring.datasource.username=root
spring.datasource.password=PleaseSQL@24112005
spring.datasource.url = jdbc:mysql://localhost:3306/collegeop
spring.jpa.hibernate.ddl-auto=update