spring.application.name=billing

spring.datasource.username=root
spring.datasource.password=PleaseSQL@24112005
spring.datasource.url = jdbc:mysql://localhost:3306/billing 
spring.jpa.hibernate.ddl-auto=update